# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20, verbose_name=b'\xe8\xa7\x92\xe8\x89\xb2\xe5\x90\x8d')),
                ('right_rule', models.CharField(max_length=20, verbose_name=b'\xe6\x9d\x83\xe9\x99\x90\xe5\x90\x8d')),
                ('description', models.CharField(max_length=200, verbose_name=b'\xe8\xaf\xb4\xe6\x98\x8e')),
                ('create_time', models.DateTimeField(max_length=50, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=20, verbose_name=b'\xe6\x9d\x83\xe9\x99\x90\xe5\x90\x8d')),
                ('rule_class', models.CharField(max_length=20, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\x88\x86\xe7\xb1\xbb')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x_admin.Role', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe8\xa7\x92\xe8\x89\xb2')),
            ],
        ),
        migrations.CreateModel(
            name='Rulegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb\xe5\x90\x8d\xe7\xa7\xb0')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x_admin.Role', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe8\xa7\x92\xe8\x89\xb2')),
                ('rulegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x_admin.Rule', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe6\x9d\x83\xe9\x99\x90')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('phone', models.CharField(max_length=11, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d')),
                ('email', models.CharField(max_length=20, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('role', models.CharField(max_length=20, verbose_name=b'\xe8\xa7\x92\xe8\x89\xb2')),
                ('create_time', models.DateTimeField(max_length=50, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('start', models.SmallIntegerField(default=1, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('roleuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x_admin.Role', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe8\xa7\x92\xe8\x89\xb2')),
                ('rulegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x_admin.Rule', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe6\x9d\x83\xe9\x99\x90')),
            ],
        ),
        migrations.CreateModel(
            name='Vipadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vipname', models.CharField(max_length=20, verbose_name=b'\xe7\xad\x89\xe7\xba\xa7\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
        ),
        migrations.CreateModel(
            name='Viplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name=b'\xe4\xbc\x9a\xe5\x91\x98\xe5\x90\x8d\xe7\xa7\xb0')),
                ('sex', models.CharField(max_length=20, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('phone', models.CharField(max_length=11, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d')),
                ('email', models.CharField(max_length=20, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x_admin.Vipadmin', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe4\xbc\x9a\xe5\x91\x98\xe7\xad\x89\xe7\xba\xa7')),
            ],
        ),
    ]
